config/routes.rb
Rails.application.routes.draw do

  get 'support/index'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-inverse.navbar-static-top{"role"=>"navigation"}
  .container-fluid
    .navbar-header
      .navbar-brand
        = link_to 'GIFMONSTER', root_path
      %button.navbar-toggle{"data-target" => "#navbar", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    / Collect the nav links, forms, and other content for toggling
    #navbar.collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Support', support_index_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>GIFMONSTER</title>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta name="description" content="Send annotated GIFs by text message">

  <%= stylesheet_link_tag  'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag  'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>


<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" %>
<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
<%= javascript_include_tag 'application'%>
<%= csrf_meta_tags %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63799801-1', 'auto');
  ga('send', 'pageview');

</script>
</head>
<body>

<%= render 'layouts/nav' %>
<%= yield %>
</div>
</body>
</html>

app/views/support/index.html.haml
.container-fluid
  .col-sm-4.col-sm-offset-4
    %h1 CONTACT US
    %h4 Questions about GIFMONSTER?
    = mail_to "gifmonster@23b.it", 'Contact us by email.', class: "mail_link"

app/views/welcome/index.html.haml
.col-sm-4.col-sm-offset-4
  .title
    %h1 GIFMONSTER

  %br
  %br

  .monster
    .monster-picture
      = image_tag("monster_noeye.png")
    .eye
      = image_tag("eyeball.png")

  %br
  %br

  .app-store-button
    .btn
      = image_tag("Download_on_the_App_Store_Badge_US-UK_135x40.svg")